/**/controller_manager:
  ros__parameters:
    update_rate: 500  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    robotiq_activation_controller:
      type: robotiq_controllers/RobotiqActivationController

/**/robotiq_gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
    max_effort: 50.0
    max_velocity: 0.5
    state_interfaces: ["position", "velocity"]
    allow_stalling: true
    stall_timeout: 0.05
    goal_tolerance: 0.02

/**/robotiq_activation_controller:
  ros__parameters:
    default: true
