/**:
  controller_manager:
    ros__parameters:
      update_rate: 125

      robotiq_force_torque_sensor_broadcaster:
        type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

  robotiq_force_torque_sensor_broadcaster:
    ros__parameters:
      sensor_name: robotiq_ft_sensor
      state_interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z
      frame_id: robotiq_ft_frame_id
